steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # --- שלב 1: Login ל-Azure באמצעות Service Principal (OIDC) ---
      # נשתמש בסט המפתחות שנוצר לפני 46 דקות
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # שים לב: העתק את ה-NAME המלא של הסודות מהרשימה שצילמת
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F0DD1CBA002D41D192EBE5BCE81B8CE1 }} 
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D5D8D9BBF20B481FAA4FE19D86F55CD9 }} 
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AC9926DB01E748F890A9CB7B767D7CB5 }}
          auth-type: 'SERVICE_PRINCIPAL'

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Medina-BackOffice'
          slot-name: 'Production'
          # אין צורך ב-publish-profile כשאנחנו עושים login מראש
          package: .
