name: Build and deploy Frontend to Azure Web App - Medina-BackOffice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # --- 1. בנייה: כניסה לתיקייה הנכונה ---
      - name: npm install, build
        run: |
          cd medina-insights-front-main
          npm install
          npm run build --if-present
      
      # אריזה של תיקיית dist
      - name: Zip artifact for deployment
        run: |
          cd medina-insights-front-main/dist
          zip -r ../../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    # הגדרת הרשאות אבטחה ל-OIDC
    permissions:
      id-token: write 
      contents: read 
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # --- 2. התחברות ל-Azure (חייב להחליף את השמות הארוכים כאן!) ---
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # העתק את ה-NAME המלא של הסודות שנוצרו ב-46 דקות האחרונות
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F0DD1CBA002D41D192EBE5BCE81B8CE1 }} 
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D5D8D9BBF20B481FAA4FE19D86F55CD9 }} 
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AC9926DB01E748F890A9CB7B767D7CB5 }}
          auth-type: 'SERVICE_PRINCIPAL'

      # --- 3. פריסה ל-Web App ---
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Medina-BackOffice'
          slot-name: 'Production'
          package: .
